# Generated by Django 6.0.6 on 2026-07-04 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
        ('projects', '0002_project_address_project_city_project_client_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='projects.project'),
        ),
    ]
