# Generated by Django 6.0.6 on 2026-07-04 06:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('current_stage', models.CharField(choices=[('Plinth', 'Plinth'), ('Slab', 'Slab'), ('Brickwork', 'Brickwork'), ('Plaster', 'Plaster'), ('Flooring', 'Flooring'), ('Finishing', 'Finishing'), ('Handover', 'Handover')], default='Plinth', max_length=20)),
                ('progress', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProgressUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('Plinth', 'Plinth'), ('Slab', 'Slab'), ('Brickwork', 'Brickwork'), ('Plaster', 'Plaster'), ('Flooring', 'Flooring'), ('Finishing', 'Finishing'), ('Handover', 'Handover')], max_length=20)),
                ('progress', models.PositiveIntegerField()),
                ('message', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='progress_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
