# Generated by Django 6.0.6 on 2026-07-04 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_address_project_city_project_client_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='location_type',
            field=models.CharField(blank=True, default='Ahmedabad', max_length=100, null=True),
        ),
    ]
