# Generated by Django 5.2.15 on 2026-07-06 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_asset_id_alter_attendance_id_alter_employee_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='client_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='flat',
            name='client_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='flat',
            name='flat_type',
            field=models.CharField(choices=[('1BHK', '1BHK'), ('2BHK', '2BHK'), ('3BHK', '3BHK'), ('4BHK', '4BHK'), ('PENTHOUSE', 'Penthouse'), ('SHOP', 'Shop'), ('OFFICE', 'Office')], default='2BHK', max_length=20),
        ),
        migrations.AddField(
            model_name='flat',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
