# Generated by Django 5.2.15 on 2026-07-06 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_flat_client_name_flat_client_phone_flat_flat_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='booking_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flat',
            name='family_members',
            field=models.TextField(blank=True, null=True),
        ),
    ]
