# Generated by Django 5.2.15 on 2026-07-07 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_flat_booking_date_flat_family_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='client_name',
        ),
    ]
