# Generated by Django 5.2.15 on 2026-07-07 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_remove_project_client_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('UNDER_CONSTRUCTION', 'Under Construction'), ('READY_TO_MOVE', 'Ready to Move'), ('COMPLETED', 'Completed'), ('OTHER', 'Other')], default='UNDER_CONSTRUCTION', max_length=20),
        ),
    ]
